### GENERAL SETTINGS ###

# Site settings
title: RailsMG
description: "Website do grupo de usuários Ruby de Minas Gerais"
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "" #important: start with /
url: ""

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#981A21" #"#F70031" 
  primary_rgb: "152,26,33" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.  
  secondary: "#000000" #"#33004D"
  link: "#981A21"
  link_hover: "#000000"
  footer_heading: "#981A21"
  footer_content: "#ffffff"

### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: github
    url: http://github.com/railsmg
  - title: twitter
    url: http://twitter.com/railsmg

# Contact email
email: railsmg@railsmg.com.br

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Rails MG"